using SYT.Fiskaly.SignDE.Exports.ValueObjects;

namespace SYT.Fiskaly.SignDE.Exports;

/// <summary>
/// The archive produced by a SIGN DE export, exactly as the provider sent it.
/// </summary>
/// <remarks>
/// <para>
/// Retrieved from <c>GET /api/v2/tss/{tss_id}/export/{export_id}/file</c>, which fiskaly's own spec describes
/// as <i>"the TAR file generated by the export operation"</i>. Its contents are the security module's own
/// records — fiskaly: <i>"the SMAERS initialization information, the signed log messages, and the certificates
/// to verify them"</i>. Concretely: ASN.1 log files named <c>Unixt_{time}_Sig-{counter}_…</c>, X.509
/// certificates, and one <c>info.csv</c> naming the module's manufacturer and firmware.
/// </para>
/// <para>
/// This is NOT a DSFinV-K export. DSFinV-K — the CSV set an auditor receives — is a separate fiskaly product
/// on a separate host, and this endpoint never produces it. The type was called <c>DsfinvkArchive</c> until
/// rc.8, which sent at least one integrator looking for a DSFinV-K API that does not exist here.
/// </para>
/// <para>
/// The bytes are kept verbatim and are not parsed. A caller archiving them for the ten-year retention duty
/// must store what the provider sent, not an interpretation of it.
/// </para>
/// </remarks>
public sealed class ExportArchive
{
    private readonly byte[] _rawContent;

    private ExportArchive(ExportId exportId, byte[] rawContent)
    {
        ExportId = exportId;
        _rawContent = rawContent;
    }

    public ExportId ExportId { get; }

    /// <summary>The archive exactly as received.</summary>
    public ReadOnlyMemory<byte> RawContent => _rawContent;

    public static async Task<ExportArchive> FromStreamAsync(
        ExportId exportId,
        Stream archiveStream,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(archiveStream);

        byte[] bytes = await ReadAllBytesAsync(archiveStream, cancellationToken).ConfigureAwait(false);
        return new ExportArchive(exportId, bytes);
    }

    public Stream OpenRawStream() => new MemoryStream(_rawContent, writable: false);

    private static async Task<byte[]> ReadAllBytesAsync(Stream stream, CancellationToken cancellationToken)
    {
        using MemoryStream buffer = new MemoryStream();
        await stream.CopyToAsync(buffer, cancellationToken).ConfigureAwait(false);
        return buffer.ToArray();
    }
}
